Repository rpm-software-management/dnf5, pull requests merged in 2023-05, with the labels that each got.

#448 Add detect_release to public API
  bindings/libdnf5/conf.i
  include/libdnf/conf/vars.hpp
  libdnf/conf/vars.cpp
Labels: ready for review

#517 transaction: Fix iterator over RPM problems
  libdnf/base/transaction.cpp
  libdnf/rpm/transaction.hpp
Labels: ready for review

#521 Connect destdir cmd option with configuration
  dnf5/commands/download/download.cpp
  dnf5/commands/download/download.hpp
  dnf5/include/dnf5/shared_options.hpp
  dnf5/shared_options.cpp
Labels: ready for review

#536 Replace runtime_error by libdnf5 error
  dnf5/main.cpp
Labels: test required

#542 Packit: use GH's release notes for downstream changelog
  .packit.yaml
Labels: ready for review

#551 comps: Possibility to create an empty EnvironmentQuery
  include/libdnf/comps/environment/query.hpp
  libdnf/comps/environment/query.cpp
Labels: ready for review

#552 goal: Split group specs resolution to separate method
  libdnf/base/goal.cpp
Labels: ready for review

#565 DNF5 should not deprecate DNF on Fedora38
  dnf5.spec
Labels: ready for review

#496 download: Resolve goal separately for each package
  dnf5/commands/download/download.cpp
Labels: ready for review

#577 Exclude dnf.conf when not installed
  dnf5.spec
Labels: ready for review, Priority: HIGH

#576 packit: keep rpm macros in specfile
  .packit.yaml
Labels: ready for review
